"""
Trade Journal — SQLite database for logging every signal, evaluation, and trade.

This is the foundation of the learning engine. Every trade gets logged with:
- All strategy signals at the time of entry
- Claude's reasoning and confidence
- Market regime
- Actual outcome (P&L, duration, max adverse/favorable excursion)
- Post-trade analysis

This data feeds the learning engine:
- Which strategies perform best per instrument?
- Which regime produces the most winners?
- What's the optimal confluence score threshold?
- Are there time-of-day patterns?
"""

import json
from datetime import datetime, timezone
from contextlib import contextmanager
from sqlalchemy import (
    create_engine, Column, String, Float, Integer, Boolean, Text, DateTime,
    MetaData, Table, Index, ForeignKey, event
)
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker, scoped_session
from ..config import config


class Base(DeclarativeBase):
    pass


class SignalLog(Base):
    """Every signal generated by the system, even if no trade was taken."""
    __tablename__ = "signal_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10), nullable=False)
    regime = Column(String(20))
    composite_score = Column(Float, default=0.0)
    direction = Column(String(10))  # LONG, SHORT, or null
    agreeing_strategies = Column(Integer, default=0)
    total_strategies = Column(Integer, default=0)
    # JSON blob of all strategy signals
    signals_json = Column(Text)
    # Claude's decision
    claude_action = Column(String(10))  # BUY, SELL, SKIP
    claude_confidence = Column(Integer, default=0)
    claude_reasoning = Column(Text)
    # Risk manager result
    risk_passed = Column(Boolean, default=False)
    risk_rejections = Column(Text)  # JSON list
    # DE-03: Data lineage — trace signal back to the specific candle
    candle_timestamp = Column(DateTime)   # Timestamp of the candle that triggered the signal
    candle_close = Column(Float)          # Close price of the triggering candle
    # Final verdict
    should_trade = Column(Boolean, default=False)

    # DE-06: Add indexes for frequently queried columns
    __table_args__ = (
        Index("idx_signal_timestamp", "timestamp"),
        Index("idx_signal_symbol", "symbol"),
    )


class TradeLog(Base):
    """Completed trades — the core of the learning engine."""
    __tablename__ = "trade_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    # DE-07: Add foreign key for referential integrity
    signal_log_id = Column(Integer, ForeignKey("signal_logs.id"))
    opened_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    closed_at = Column(DateTime)
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10))
    direction = Column(String(10))  # LONG or SHORT
    regime = Column(String(20))
    # Prices
    entry_price = Column(Float)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    exit_price = Column(Float)
    position_size = Column(Float)
    # Results
    pnl = Column(Float, default=0.0)
    pnl_pct = Column(Float, default=0.0)
    duration_seconds = Column(Integer, default=0)
    max_favorable = Column(Float, default=0.0)  # Best unrealized P&L
    max_adverse = Column(Float, default=0.0)     # Worst unrealized P&L
    exit_reason = Column(String(20))  # tp_hit, sl_hit, manual, time
    # Strategy context
    confluence_score = Column(Float, default=0.0)
    claude_confidence = Column(Integer, default=0)
    strategies_agreed = Column(Text)  # JSON list of strategy names that agreed
    # Learning
    outcome_grade = Column(String(1))  # A, B, C, D, F
    lessons_learned = Column(Text)     # Claude's post-trade analysis

    # DE-06: Indexes for frequently queried columns
    __table_args__ = (
        Index("idx_trade_opened_at", "opened_at"),
        Index("idx_trade_symbol", "symbol"),
        Index("idx_trade_symbol_opened", "symbol", "opened_at"),
        Index("idx_trade_exit_price", "exit_price"),  # DE-F06
    )


class PerformanceSnapshot(Base):
    """Daily performance snapshots for the learning engine."""
    __tablename__ = "performance_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(String(10), nullable=False, unique=True)
    balance = Column(Float)
    total_pnl = Column(Float)
    daily_pnl = Column(Float)
    trades_count = Column(Integer, default=0)
    wins = Column(Integer, default=0)
    losses = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)
    avg_win = Column(Float, default=0.0)
    avg_loss = Column(Float, default=0.0)
    best_strategy = Column(String(50))
    worst_strategy = Column(String(50))
    regime = Column(String(20))


class RiskState(Base):
    """
    Persisted risk manager state (Fix #8).
    Survives engine restarts so balance and daily P&L aren't lost.
    """
    __tablename__ = "risk_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    starting_balance = Column(Float, default=100000.0)
    current_balance = Column(Float, default=100000.0)
    total_pnl = Column(Float, default=0.0)
    peak_balance = Column(Float, default=100000.0)


class PredictionLog(Base):
    """
    Every prediction the system makes — tracked like ML predictions.

    A "prediction" is any signal where the system says LONG or SHORT.
    After N candles, we check: was the prediction correct?
    This gives us an accuracy score like ML model evaluation.
    """
    __tablename__ = "prediction_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10))
    strategy_name = Column(String(50))       # Individual strategy or "confluence"
    predicted_direction = Column(String(10))  # LONG or SHORT
    entry_price = Column(Float)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    confluence_score = Column(Float, default=0.0)
    regime = Column(String(20))
    # Outcome (filled in when resolved)
    actual_direction = Column(String(10))     # Did price actually go LONG or SHORT?
    outcome = Column(String(20))              # tp_hit, sl_hit, direction_correct, direction_wrong
    price_after_n = Column(Float)             # Price N candles later
    max_favorable = Column(Float, default=0.0)
    max_adverse = Column(Float, default=0.0)
    direction_correct = Column(Boolean)       # Was the direction prediction right?
    target_hit = Column(Boolean)              # Did TP get hit before SL?
    resolved = Column(Boolean, default=False)
    resolved_at = Column(DateTime)
    candles_to_resolve = Column(Integer)      # How many candles until SL/TP/timeout

    # DE-06: Index for pending prediction queries
    __table_args__ = (
        Index("idx_prediction_resolved", "resolved"),
        Index("idx_prediction_timestamp", "timestamp"),
    )


class ABTest(Base):
    """A/B test configuration — shadow-mode parameter comparison."""
    __tablename__ = "ab_tests"

    id = Column(Integer, primary_key=True, autoincrement=True)
    test_name = Column(String(100), unique=True, nullable=False)
    param_name = Column(String(100))
    variant_a_value = Column(Text)
    variant_b_value = Column(Text)
    description = Column(Text, default="")
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    status = Column(String(20), default="active")  # active, completed, cancelled


class ABTestResult(Base):
    """Individual result entries for A/B test variants."""
    __tablename__ = "ab_test_results"

    id = Column(Integer, primary_key=True, autoincrement=True)
    test_id = Column(Integer, ForeignKey("ab_tests.id"))
    variant = Column(String(1))  # "A" or "B"
    symbol = Column(String(20))
    prediction = Column(String(20))
    outcome = Column(String(20))
    pnl = Column(Float, default=0.0)
    won = Column(Boolean, default=False)
    metadata_json = Column(Text, default="{}")
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class TokenUsage(Base):
    """
    Track every Claude API call — tokens used and estimated cost.

    Two categories:
    - "runtime": API calls the trading engine makes (trade analysis, reviews)
    - "build": Estimated cost of Claude Code sessions building this system
    """
    __tablename__ = "token_usage"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    category = Column(String(20))             # "runtime" or "build"
    purpose = Column(String(50))              # trade_analysis, weekly_review, evaluation, etc.
    model = Column(String(50))
    tokens_in = Column(Integer, default=0)
    tokens_out = Column(Integer, default=0)
    estimated_cost_usd = Column(Float, default=0.0)
    metadata_json = Column(Text)              # Optional JSON context


# CQ-01 FIX: Replace singleton session with session factory.
# Supports multiple database instances (production + lab).
_engines: dict[str, object] = {}
_factories: dict[str, object] = {}

# Default DB key
_active_db_key = "default"
_engine = None
_SessionFactory = None


def _init_db(db_key: str = "default", db_path: str | None = None):
    """Initialize a database engine and session factory.

    Args:
        db_key: Identifier for this DB instance ("default" for production, "lab" for lab).
        db_path: SQLite path override. If None, uses config.db_url.
    """
    global _engine, _SessionFactory, _active_db_key

    if db_key in _engines:
        _engine = _engines[db_key]
        _SessionFactory = _factories[db_key]
        _active_db_key = db_key
        return

    if db_path is None:
        db_path = config.db_url.replace("sqlite+aiosqlite:///", "sqlite:///")
    elif not db_path.startswith("sqlite"):
        db_path = f"sqlite:///{db_path}"

    eng = create_engine(db_path, echo=False)

    # Enable WAL mode for better concurrent read/write performance
    @event.listens_for(eng, "connect")
    def set_sqlite_pragma(dbapi_conn, connection_record):
        cursor = dbapi_conn.cursor()
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.close()

    Base.metadata.create_all(eng)
    factory = scoped_session(sessionmaker(bind=eng))

    _engines[db_key] = eng
    _factories[db_key] = factory
    _engine = eng
    _SessionFactory = factory
    _active_db_key = db_key


def init_lab_db(db_path: str | None = None):
    """Initialize the Lab database (separate from production).

    Call this at Lab engine startup. Uses a separate SQLite file
    so lab trades don't contaminate production data.
    """
    import os
    if db_path is None:
        db_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
            "notas_lave_lab.db"
        )
    _init_db(db_key="lab", db_path=db_path)


def use_db(db_key: str = "default"):
    """Switch which database subsequent get_db() calls use."""
    global _engine, _SessionFactory, _active_db_key
    if db_key in _engines:
        _engine = _engines[db_key]
        _SessionFactory = _factories[db_key]
        _active_db_key = db_key
    else:
        _init_db(db_key)


def get_db() -> Session:
    """
    Get a database session. Thread-safe via scoped_session.

    CQ-01: Each thread gets its own session from the factory.
    Sessions should be committed/rolled back by the caller.
    For simple read operations, the session auto-commits on close.

    NOTE: Prefer get_session() context manager for new code — it
    automatically commits/rollbacks/closes the session.
    """
    _init_db()
    return _SessionFactory()


@contextmanager
def get_session():
    """CQ-01: Context manager for short-lived sessions.

    Usage:
        with get_session() as db:
            db.query(...)
            db.commit()

    Sessions are automatically closed after the block, preventing
    stale data and resource leaks. Rollback on exception.
    """
    _init_db()
    session = _SessionFactory()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


def log_signal(
    symbol: str,
    timeframe: str,
    regime: str,
    composite_score: float,
    direction: str | None,
    agreeing: int,
    total: int,
    signals: list[dict],
    claude_action: str,
    claude_confidence: int,
    claude_reasoning: str,
    risk_passed: bool,
    risk_rejections: list[str],
    should_trade: bool,
) -> int:
    """Log a signal evaluation. Returns the log ID."""
    db = get_db()
    entry = SignalLog(
        symbol=symbol,
        timeframe=timeframe,
        regime=regime,
        composite_score=composite_score,
        direction=direction,
        agreeing_strategies=agreeing,
        total_strategies=total,
        signals_json=json.dumps(signals),
        claude_action=claude_action,
        claude_confidence=claude_confidence,
        claude_reasoning=claude_reasoning,
        risk_passed=risk_passed,
        risk_rejections=json.dumps(risk_rejections),
        should_trade=should_trade,
    )
    db.add(entry)
    db.commit()
    return entry.id


def log_trade(
    signal_log_id: int,
    symbol: str,
    timeframe: str,
    direction: str,
    regime: str,
    entry_price: float,
    stop_loss: float,
    take_profit: float,
    position_size: float,
    confluence_score: float,
    claude_confidence: int,
    strategies_agreed: list[str],
) -> int:
    """Log a new trade. Returns the trade ID."""
    db = get_db()
    trade = TradeLog(
        signal_log_id=signal_log_id,
        symbol=symbol,
        timeframe=timeframe,
        direction=direction,
        regime=regime,
        entry_price=entry_price,
        stop_loss=stop_loss,
        take_profit=take_profit,
        position_size=position_size,
        confluence_score=confluence_score,
        claude_confidence=claude_confidence,
        strategies_agreed=json.dumps(strategies_agreed),
    )
    db.add(trade)
    db.commit()
    return trade.id


def close_trade(
    trade_id: int,
    exit_price: float,
    exit_reason: str,
    pnl: float,
    pnl_pct: float,
    duration_seconds: int,
    max_favorable: float = 0.0,
    max_adverse: float = 0.0,
):
    """Record trade outcome when it closes."""
    db = get_db()
    trade = db.query(TradeLog).filter(TradeLog.id == trade_id).first()
    if trade:
        trade.exit_price = exit_price
        trade.exit_reason = exit_reason
        trade.pnl = pnl
        trade.pnl_pct = pnl_pct
        trade.duration_seconds = duration_seconds
        trade.max_favorable = max_favorable
        trade.max_adverse = max_adverse
        trade.closed_at = datetime.now(timezone.utc)
        db.commit()


def get_recent_signals(limit: int = 50) -> list[dict]:
    """Get recent signal logs for the dashboard."""
    db = get_db()
    logs = db.query(SignalLog).order_by(SignalLog.id.desc()).limit(limit).all()
    return [
        {
            "id": l.id,
            "timestamp": l.timestamp.isoformat() if l.timestamp else None,
            "symbol": l.symbol,
            "timeframe": l.timeframe,
            "regime": l.regime,
            "score": l.composite_score,
            "direction": l.direction,
            "claude_action": l.claude_action,
            "claude_confidence": l.claude_confidence,
            "should_trade": l.should_trade,
        }
        for l in logs
    ]


def get_recent_trades(limit: int = 50) -> list[dict]:
    """Get recent trades for the dashboard."""
    db = get_db()
    trades = db.query(TradeLog).order_by(TradeLog.id.desc()).limit(limit).all()
    return [
        {
            "id": t.id,
            "opened_at": t.opened_at.isoformat() if t.opened_at else None,
            "closed_at": t.closed_at.isoformat() if t.closed_at else None,
            "symbol": t.symbol,
            "direction": t.direction,
            "regime": t.regime,
            "entry": t.entry_price,
            "exit": t.exit_price,
            "pnl": t.pnl,
            "pnl_pct": t.pnl_pct,
            "exit_reason": t.exit_reason,
            "confluence_score": t.confluence_score,
            "claude_confidence": t.claude_confidence,
            "grade": t.outcome_grade,
        }
        for t in trades
    ]


def get_strategy_performance() -> list[dict]:
    """Analyze which strategies contribute most to winning trades."""
    db = get_db()
    trades = db.query(TradeLog).filter(TradeLog.exit_price.isnot(None)).all()

    strategy_stats: dict[str, dict] = {}
    for t in trades:
        if not t.strategies_agreed:
            continue
        strategies = json.loads(t.strategies_agreed)
        for s in strategies:
            if s not in strategy_stats:
                strategy_stats[s] = {"wins": 0, "losses": 0, "total_pnl": 0.0}
            if t.pnl and t.pnl > 0:
                strategy_stats[s]["wins"] += 1
            else:
                strategy_stats[s]["losses"] += 1
            strategy_stats[s]["total_pnl"] += t.pnl or 0

    return [
        {
            "strategy": name,
            "wins": stats["wins"],
            "losses": stats["losses"],
            "total_trades": stats["wins"] + stats["losses"],
            "win_rate": stats["wins"] / max(stats["wins"] + stats["losses"], 1) * 100,
            "total_pnl": round(stats["total_pnl"], 2),
        }
        for name, stats in sorted(strategy_stats.items(), key=lambda x: x[1]["total_pnl"], reverse=True)
    ]


def save_risk_state(starting_balance: float, current_balance: float, total_pnl: float, peak_balance: float):
    """Save risk manager state to DB so it survives restarts (Fix #8)."""
    db = get_db()
    state = db.query(RiskState).first()
    if state:
        state.starting_balance = starting_balance
        state.current_balance = current_balance
        state.total_pnl = total_pnl
        state.peak_balance = peak_balance
        state.updated_at = datetime.now(timezone.utc)
    else:
        db.add(RiskState(
            starting_balance=starting_balance,
            current_balance=current_balance,
            total_pnl=total_pnl,
            peak_balance=peak_balance,
        ))
    db.commit()


def load_risk_state() -> dict | None:
    """Load risk state from DB on startup (Fix #8)."""
    db = get_db()
    state = db.query(RiskState).first()
    if state:
        return {
            "starting_balance": state.starting_balance,
            "current_balance": state.current_balance,
            "total_pnl": state.total_pnl,
            "peak_balance": state.peak_balance,
        }
    return None
