"""
Trade Journal — SQLite database for logging every signal, evaluation, and trade.

This is the foundation of the learning engine. Every trade gets logged with:
- All strategy signals at the time of entry
- Claude's reasoning and confidence
- Market regime
- Actual outcome (P&L, duration, max adverse/favorable excursion)
- Post-trade analysis

This data feeds the learning engine:
- Which strategies perform best per instrument?
- Which regime produces the most winners?
- What's the optimal confluence score threshold?
- Are there time-of-day patterns?
"""

import json
from datetime import datetime, timezone
from sqlalchemy import (
    create_engine, Column, String, Float, Integer, Boolean, Text, DateTime,
    MetaData, Table
)
from sqlalchemy.orm import DeclarativeBase, Session
from ..config import config


class Base(DeclarativeBase):
    pass


class SignalLog(Base):
    """Every signal generated by the system, even if no trade was taken."""
    __tablename__ = "signal_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10), nullable=False)
    regime = Column(String(20))
    composite_score = Column(Float, default=0.0)
    direction = Column(String(10))  # LONG, SHORT, or null
    agreeing_strategies = Column(Integer, default=0)
    total_strategies = Column(Integer, default=0)
    # JSON blob of all strategy signals
    signals_json = Column(Text)
    # Claude's decision
    claude_action = Column(String(10))  # BUY, SELL, SKIP
    claude_confidence = Column(Integer, default=0)
    claude_reasoning = Column(Text)
    # Risk manager result
    risk_passed = Column(Boolean, default=False)
    risk_rejections = Column(Text)  # JSON list
    # Final verdict
    should_trade = Column(Boolean, default=False)


class TradeLog(Base):
    """Completed trades — the core of the learning engine."""
    __tablename__ = "trade_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_log_id = Column(Integer)  # Links to the signal that created this trade
    opened_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    closed_at = Column(DateTime)
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10))
    direction = Column(String(10))  # LONG or SHORT
    regime = Column(String(20))
    # Prices
    entry_price = Column(Float)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    exit_price = Column(Float)
    position_size = Column(Float)
    # Results
    pnl = Column(Float, default=0.0)
    pnl_pct = Column(Float, default=0.0)
    duration_seconds = Column(Integer, default=0)
    max_favorable = Column(Float, default=0.0)  # Best unrealized P&L
    max_adverse = Column(Float, default=0.0)     # Worst unrealized P&L
    exit_reason = Column(String(20))  # tp_hit, sl_hit, manual, time
    # Strategy context
    confluence_score = Column(Float, default=0.0)
    claude_confidence = Column(Integer, default=0)
    strategies_agreed = Column(Text)  # JSON list of strategy names that agreed
    # Learning
    outcome_grade = Column(String(1))  # A, B, C, D, F
    lessons_learned = Column(Text)     # Claude's post-trade analysis


class PerformanceSnapshot(Base):
    """Daily performance snapshots for the learning engine."""
    __tablename__ = "performance_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(String(10), nullable=False, unique=True)  # YYYY-MM-DD
    balance = Column(Float)
    total_pnl = Column(Float)
    daily_pnl = Column(Float)
    trades_count = Column(Integer, default=0)
    wins = Column(Integer, default=0)
    losses = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)
    avg_win = Column(Float, default=0.0)
    avg_loss = Column(Float, default=0.0)
    best_strategy = Column(String(50))
    worst_strategy = Column(String(50))
    regime = Column(String(20))


# Database connection
_engine = None
_session = None


def get_db() -> Session:
    """Get the database session. Creates tables on first call."""
    global _engine, _session
    if _engine is None:
        # Use sync SQLite for simplicity (async adds complexity with no benefit for journal)
        db_path = config.db_url.replace("sqlite+aiosqlite:///", "sqlite:///")
        _engine = create_engine(db_path, echo=False)
        Base.metadata.create_all(_engine)
    if _session is None:
        _session = Session(_engine)
    return _session


def log_signal(
    symbol: str,
    timeframe: str,
    regime: str,
    composite_score: float,
    direction: str | None,
    agreeing: int,
    total: int,
    signals: list[dict],
    claude_action: str,
    claude_confidence: int,
    claude_reasoning: str,
    risk_passed: bool,
    risk_rejections: list[str],
    should_trade: bool,
) -> int:
    """Log a signal evaluation. Returns the log ID."""
    db = get_db()
    entry = SignalLog(
        symbol=symbol,
        timeframe=timeframe,
        regime=regime,
        composite_score=composite_score,
        direction=direction,
        agreeing_strategies=agreeing,
        total_strategies=total,
        signals_json=json.dumps(signals),
        claude_action=claude_action,
        claude_confidence=claude_confidence,
        claude_reasoning=claude_reasoning,
        risk_passed=risk_passed,
        risk_rejections=json.dumps(risk_rejections),
        should_trade=should_trade,
    )
    db.add(entry)
    db.commit()
    return entry.id


def log_trade(
    signal_log_id: int,
    symbol: str,
    timeframe: str,
    direction: str,
    regime: str,
    entry_price: float,
    stop_loss: float,
    take_profit: float,
    position_size: float,
    confluence_score: float,
    claude_confidence: int,
    strategies_agreed: list[str],
) -> int:
    """Log a new trade. Returns the trade ID."""
    db = get_db()
    trade = TradeLog(
        signal_log_id=signal_log_id,
        symbol=symbol,
        timeframe=timeframe,
        direction=direction,
        regime=regime,
        entry_price=entry_price,
        stop_loss=stop_loss,
        take_profit=take_profit,
        position_size=position_size,
        confluence_score=confluence_score,
        claude_confidence=claude_confidence,
        strategies_agreed=json.dumps(strategies_agreed),
    )
    db.add(trade)
    db.commit()
    return trade.id


def close_trade(
    trade_id: int,
    exit_price: float,
    exit_reason: str,
    pnl: float,
    pnl_pct: float,
    duration_seconds: int,
    max_favorable: float = 0.0,
    max_adverse: float = 0.0,
):
    """Record trade outcome when it closes."""
    db = get_db()
    trade = db.query(TradeLog).filter(TradeLog.id == trade_id).first()
    if trade:
        trade.exit_price = exit_price
        trade.exit_reason = exit_reason
        trade.pnl = pnl
        trade.pnl_pct = pnl_pct
        trade.duration_seconds = duration_seconds
        trade.max_favorable = max_favorable
        trade.max_adverse = max_adverse
        trade.closed_at = datetime.now(timezone.utc)
        db.commit()


def get_recent_signals(limit: int = 50) -> list[dict]:
    """Get recent signal logs for the dashboard."""
    db = get_db()
    logs = db.query(SignalLog).order_by(SignalLog.id.desc()).limit(limit).all()
    return [
        {
            "id": l.id,
            "timestamp": l.timestamp.isoformat() if l.timestamp else None,
            "symbol": l.symbol,
            "timeframe": l.timeframe,
            "regime": l.regime,
            "score": l.composite_score,
            "direction": l.direction,
            "claude_action": l.claude_action,
            "claude_confidence": l.claude_confidence,
            "should_trade": l.should_trade,
        }
        for l in logs
    ]


def get_recent_trades(limit: int = 50) -> list[dict]:
    """Get recent trades for the dashboard."""
    db = get_db()
    trades = db.query(TradeLog).order_by(TradeLog.id.desc()).limit(limit).all()
    return [
        {
            "id": t.id,
            "opened_at": t.opened_at.isoformat() if t.opened_at else None,
            "closed_at": t.closed_at.isoformat() if t.closed_at else None,
            "symbol": t.symbol,
            "direction": t.direction,
            "regime": t.regime,
            "entry": t.entry_price,
            "exit": t.exit_price,
            "pnl": t.pnl,
            "pnl_pct": t.pnl_pct,
            "exit_reason": t.exit_reason,
            "confluence_score": t.confluence_score,
            "claude_confidence": t.claude_confidence,
            "grade": t.outcome_grade,
        }
        for t in trades
    ]


def get_strategy_performance() -> list[dict]:
    """Analyze which strategies contribute most to winning trades."""
    db = get_db()
    trades = db.query(TradeLog).filter(TradeLog.exit_price.isnot(None)).all()

    strategy_stats: dict[str, dict] = {}
    for t in trades:
        if not t.strategies_agreed:
            continue
        strategies = json.loads(t.strategies_agreed)
        for s in strategies:
            if s not in strategy_stats:
                strategy_stats[s] = {"wins": 0, "losses": 0, "total_pnl": 0.0}
            if t.pnl and t.pnl > 0:
                strategy_stats[s]["wins"] += 1
            else:
                strategy_stats[s]["losses"] += 1
            strategy_stats[s]["total_pnl"] += t.pnl or 0

    return [
        {
            "strategy": name,
            "wins": stats["wins"],
            "losses": stats["losses"],
            "total_trades": stats["wins"] + stats["losses"],
            "win_rate": stats["wins"] / max(stats["wins"] + stats["losses"], 1) * 100,
            "total_pnl": round(stats["total_pnl"], 2),
        }
        for name, stats in sorted(strategy_stats.items(), key=lambda x: x[1]["total_pnl"], reverse=True)
    ]
