/**
 * Strategy information for the dashboard.
 * Displayed as tooltips and info panels so you can learn while trading.
 */

export interface StrategyInfo {
  name: string;
  displayName: string;
  category: string;
  description: string;
  howItWorks: string;
  bestFor: string;
  avoid: string;
  winRate: string;
  riskReward: string;
}

export const STRATEGY_INFO: Record<string, StrategyInfo> = {
  ema_crossover: {
    name: "ema_crossover",
    displayName: "EMA Crossover",
    category: "Scalping",
    description: "Triple EMA (9/21/50) crossover with 200 EMA trend filter.",
    howItWorks: "BUY when fast EMA (9) crosses above medium EMA (21) and all 4 EMAs are stacked bullish (9>21>50>200). SELL when reversed. The 200 EMA filters out counter-trend trades.",
    bestFor: "Trending markets — Gold and BTC during strong directional moves.",
    avoid: "Ranging/sideways markets. EMAs whipsaw and generate false signals in chop.",
    winRate: "55-65%",
    riskReward: "1:2",
  },
  rsi_divergence: {
    name: "rsi_divergence",
    displayName: "RSI Divergence",
    category: "Scalping",
    description: "Detects momentum divergence using fast RSI (7-period).",
    howItWorks: "BULLISH: Price makes a lower low but RSI makes a higher low — sellers are weakening. BEARISH: Price makes a higher high but RSI makes a lower high — buyers are weakening. These divergences often precede reversals.",
    bestFor: "Gold (extremely responsive), volatile crypto. Works at range extremes.",
    avoid: "Strong trends where divergence can persist for a long time before reversing.",
    winRate: "55-65%",
    riskReward: "1:2",
  },
  bollinger_bands: {
    name: "bollinger_bands",
    displayName: "Bollinger Bands",
    category: "Scalping",
    description: "Mean reversion when price touches and re-enters the bands.",
    howItWorks: "BUY when price closes below lower band then the next candle closes back inside (bounce). SELL when price closes above upper band then re-enters. Target: middle band (20 SMA). ~95% of price stays within the bands.",
    bestFor: "Ranging markets, Asian session, consolidation periods.",
    avoid: "Strong trends — overbought can stay overbought. The band touch becomes a breakout, not a reversal.",
    winRate: "65-75% in ranges",
    riskReward: "1:1 to 1:1.5",
  },
  stochastic_scalping: {
    name: "stochastic_scalping",
    displayName: "Stochastic",
    category: "Scalping",
    description: "Fast Stochastic (5,3,3) crossover in overbought/oversold zones.",
    howItWorks: "BUY when %K crosses above %D below 20 (oversold bounce). SELL when %K crosses below %D above 80 (overbought rejection). Measures where price is relative to its recent range.",
    bestFor: "Ranging markets. 70-80% win rate in consolidation.",
    avoid: "Trends! In a strong uptrend, Stochastic stays overbought for days. Never fight the trend with this.",
    winRate: "70-80% ranging, 40-50% trending",
    riskReward: "1:1 to 1:1.5",
  },
  vwap_scalping: {
    name: "vwap_scalping",
    displayName: "VWAP Scalping",
    category: "Volume",
    description: "Bounce/rejection from Volume-Weighted Average Price.",
    howItWorks: "VWAP = average price weighted by volume. Institutions use it as a benchmark. BUY when price is above VWAP, pulls back TO it, and bounces with volume. SELL when below VWAP, rallies to it, and rejects.",
    bestFor: "First 1-2 hours of a session. Indices, liquid forex, Gold during London/NY.",
    avoid: "End of session (VWAP becomes unreliable). Low-volume periods.",
    winRate: "60-70%",
    riskReward: "1:1.5",
  },
  fibonacci_golden_zone: {
    name: "fibonacci_golden_zone",
    displayName: "Fibonacci Golden Zone",
    category: "Fibonacci",
    description: "Entry at the 50%-61.8% retracement of an impulse move.",
    howItWorks: "After a strong move up, price often retraces to 50-61.8% before continuing. This 'Golden Zone' is where institutions reload positions. Enter on a reversal candle (hammer, engulfing) within the zone. Stop below 78.6%.",
    bestFor: "All trending markets. Gold, crypto, forex during clear impulse moves.",
    avoid: "Choppy markets with no clear swings. Needs a strong impulse to draw fibs from.",
    winRate: "60-70%",
    riskReward: "1:2 to 1:3",
  },
  session_killzone: {
    name: "session_killzone",
    displayName: "ICT Kill Zone",
    category: "ICT / Smart Money",
    description: "Asian range liquidity sweep during London/NY sessions.",
    howItWorks: "Asian session (00-08 UTC) builds a range. London/NY sessions sweep above/below that range to grab stop losses, then reverse. We wait for the sweep + reversal, not the initial breakout (which is usually fake).",
    bestFor: "Gold (responds extremely well), GBPUSD, EURUSD. London open is most powerful.",
    avoid: "Trading the initial breakout — it's usually a trap. Wait for the reversal.",
    winRate: "60-70%",
    riskReward: "1:2 to 1:3",
  },
  order_block_fvg: {
    name: "order_block_fvg",
    displayName: "Order Blocks + FVG",
    category: "ICT / Smart Money",
    description: "Institutional order blocks with Fair Value Gap confluence.",
    howItWorks: "ORDER BLOCK: The last opposite candle before a strong impulse (where institutions placed orders). FVG: A 3-candle gap showing imbalance. When price returns to an OB that overlaps with an FVG, it's the highest probability ICT setup.",
    bestFor: "Gold, BTC, major forex during active sessions. Needs volatility for FVGs to form.",
    avoid: "Low-volatility quiet markets where no impulse moves occur.",
    winRate: "55-65% (OB+FVG), 45-55% (standalone)",
    riskReward: "1:2.5",
  },
  camarilla_pivots: {
    name: "camarilla_pivots",
    displayName: "Camarilla Pivots",
    category: "Scalping",
    description: "Range reversal at S3/R3 levels, breakout at S4/R4.",
    howItWorks: "Calculate Camarilla levels from yesterday's H/L/C. RANGE MODE (70% of days): Long at S3 support, Short at R3 resistance, target central pivot. BREAKOUT MODE: If price blows through R4 (bullish) or S4 (bearish), ride the momentum.",
    bestFor: "Intraday scalping, first 2-3 hours of session. Gold, Forex.",
    avoid: "News events — levels get blown through with no respect.",
    winRate: "70-80% range mode",
    riskReward: "1:1.5",
  },
  ema_gold: {
    name: "ema_gold",
    displayName: "EMA 200/1000 Gold",
    category: "Scalping",
    description: "Gold-specific pullback entry at EMA 200 with EMA 1000 trend filter.",
    howItWorks: "EMA 200 > EMA 1000 = confirmed uptrend, only go LONG. Wait for pullback to EMA 200 (institutional support). Enter on bullish bounce candle. EMA 200 is the most respected intraday level by institutions.",
    bestFor: "Gold (specifically designed for it), Silver. 5M/15M timeframes during London-NY overlap.",
    avoid: "When EMAs are flat or tangled — market is ranging, no edge.",
    winRate: "60-70%",
    riskReward: "1:1.5 to 1:2",
  },
  london_breakout: {
    name: "london_breakout",
    displayName: "London Breakout",
    category: "ICT / Smart Money",
    description: "First-hour London range breakout with retest entry.",
    howItWorks: "Mark the range from 08:00-09:00 UTC (London open). Wait for a strong breakout candle (body >70%). Don't chase — wait for price to RETEST the broken level. Enter on the retest. Waiting improves win rate by 10-15%.",
    bestFor: "Gold, EUR/USD, GBP/USD. London is the most volatile session.",
    avoid: "Low-volatility days with tiny London range. Also avoid chasing the first breakout.",
    winRate: "55-65%",
    riskReward: "1:2 to 1:3",
  },
  ny_open_range: {
    name: "ny_open_range",
    displayName: "NY Open Range",
    category: "ICT / Smart Money",
    description: "Pre-market squeeze breakout at NY open (9:30 EST).",
    howItWorks: "Mark the 9:26-9:30 AM EST range (pre-market squeeze). At 9:30 institutional algorithms trigger. First 5M candle that breaks the range with >60% body = entry. Golden hour 9:30-10:30 is when 60%+ of daily volume occurs.",
    bestFor: "Gold (extremely effective), indices, BTC. The golden hour is the most predictable 60 minutes.",
    avoid: "Wide pre-open ranges (>0.3%) — no compression means no explosive breakout.",
    winRate: "60-70%",
    riskReward: "1:2 to 1:3",
  },
  break_retest: {
    name: "break_retest",
    displayName: "Break & Retest",
    category: "Breakout",
    description: "Breakout from consolidation with retest entry and engulfing confirmation.",
    howItWorks: "Find a 20+ candle consolidation zone. Wait for breakout (body >70%, volume >1.5x). Don't chase — wait for retest of the broken level. Enter on engulfing candle at retest. Broken resistance becomes support (and vice versa). 200 EMA confirms trend.",
    bestFor: "All instruments. The retest gives tight stops and 1:2-1:3 R:R.",
    avoid: "News events — breakouts during news are unreliable for retest patterns.",
    winRate: "65-75%",
    riskReward: "1:2 to 1:3",
  },
  momentum_breakout: {
    name: "momentum_breakout",
    displayName: "Momentum Breakout",
    category: "Breakout",
    description: "Strong candle breaking S/R with ATR-based risk management.",
    howItWorks: "Wait for a POWERFUL candle: range >= 2x ATR, body >70%, volume >1.5x average. This indicates institutional conviction. Stop = 1.5x ATR (adapts to volatility). Target = 3x ATR. If volatility expanding, reduce position size.",
    bestFor: "Trending days, after consolidation. Gold, BTC, indices.",
    avoid: "Low-volume sessions. Never force a breakout — let it come to you.",
    winRate: "50-60%",
    riskReward: "1:3+",
  },
  // Composite Strategies (Arena v3)
  trend_momentum: {
    name: "trend_momentum",
    displayName: "Trend Momentum",
    category: "Composite",
    description: "Multi-indicator trend following with confluence scoring.",
    howItWorks: "Combines ADX trend strength, EMA alignment, MACD momentum, and volume confirmation. Enters on pullbacks in established trends with high confluence.",
    bestFor: "Strong trending markets, BTC/ETH during directional moves.",
    avoid: "Ranging markets where trend indicators whipsaw.",
    winRate: "55-65%",
    riskReward: "1:2 to 1:3",
  },
  mean_reversion: {
    name: "mean_reversion",
    displayName: "Mean Reversion",
    category: "Composite",
    description: "Statistical reversion to mean with Bollinger Bands, RSI, and volume.",
    howItWorks: "Identifies overextended moves using BB touches, RSI extremes, and Stochastic. Enters on reversal confirmation candles.",
    bestFor: "Ranging markets, consolidation periods.",
    avoid: "Strong trends where 'overbought can stay overbought'.",
    winRate: "60-70%",
    riskReward: "1:1.5 to 1:2",
  },
  level_confluence: {
    name: "level_confluence",
    displayName: "Level Confluence",
    category: "Composite",
    description: "Support/resistance confluence from multiple timeframes and Fibonacci levels.",
    howItWorks: "Identifies high-probability levels where multiple S/R zones, pivot points, and Fib retracements align. Waits for confirmation.",
    bestFor: "All market conditions when price approaches key levels.",
    avoid: "Low-confluence areas with scattered indicators.",
    winRate: "60-70%",
    riskReward: "1:2 to 1:3",
  },
  breakout_system: {
    name: "breakout_system",
    displayName: "Breakout System",
    category: "Composite",
    description: "Volume-confirmed breakouts from consolidation zones.",
    howItWorks: "Detects consolidation, waits for breakout with volume >1.5x average and strong candle. Enters on retest when possible.",
    bestFor: "After consolidation periods, session opens (London/NY).",
    avoid: "Low-volume periods where breakouts lack follow-through.",
    winRate: "55-65%",
    riskReward: "1:2 to 1:3",
  },
  williams_system: {
    name: "williams_system",
    displayName: "Williams System",
    category: "Composite",
    description: "Larry Williams-inspired momentum system with multiple timeframe confirmation.",
    howItWorks: "Uses Williams %R, volatility analysis, and multi-TF trend alignment. Enters on momentum continuation.",
    bestFor: "Volatile markets, trending conditions.",
    avoid: "Low-volatility quiet periods.",
    winRate: "50-60%",
    riskReward: "1:2 to 1:3",
  },
  order_flow_system: {
    name: "order_flow_system",
    displayName: "Order Flow System",
    category: "Composite",
    description: "Order book imbalance, trade flow, and funding rate analysis.",
    howItWorks: "Analyzes order book depth, recent trades, funding rates, and open interest to detect institutional positioning.",
    bestFor: "Crypto futures with visible order flow data.",
    avoid: "Low-liquidity markets with thin order books.",
    winRate: "55-65%",
    riskReward: "1:2 to 1:3",
  },
  unknown: {
    name: "unknown",
    displayName: "Unknown Strategy",
    category: "Legacy",
    description: "Strategy name not recorded (old trades before proposing_strategy tracking).",
    howItWorks: "Historical trades from before strategy attribution was implemented.",
    bestFor: "N/A",
    avoid: "N/A",
    winRate: "N/A",
    riskReward: "N/A",
  },
};

export const REGIME_INFO: Record<string, { description: string; bestStrategies: string; avoid: string }> = {
  TRENDING: {
    description: "Market is making higher highs/lower lows with directional momentum.",
    bestStrategies: "EMA Crossover, EMA 200/1000 Gold, Fibonacci, Momentum Breakout, Break & Retest",
    avoid: "Bollinger Bands, Stochastic, Camarilla range mode (mean-reversion fails in trends)",
  },
  RANGING: {
    description: "Market is moving sideways within a range, no clear direction.",
    bestStrategies: "Bollinger Bands, Stochastic, VWAP, Camarilla Pivots (S3/R3), RSI Divergence",
    avoid: "EMA Crossover (whipsaws), Momentum Breakout (no follow-through)",
  },
  VOLATILE: {
    description: "Large price swings with expanding ATR. Uncertain direction.",
    bestStrategies: "VWAP, Order Blocks, Momentum Breakout (ATR adapts), reduce position size",
    avoid: "Tight stop strategies (will get stopped out by volatility)",
  },
  QUIET: {
    description: "Low volatility, small price movements, ATR contracting.",
    bestStrategies: "Scalping (Stochastic, BB, Camarilla), wait for London/NY breakout",
    avoid: "Breakout strategies (no momentum to sustain them)",
  },
};
