"""
Trade Journal — SQLite database for logging every signal, evaluation, and trade.

This is the foundation of the learning engine. Every trade gets logged with:
- All strategy signals at the time of entry
- Claude's reasoning and confidence
- Market regime
- Actual outcome (P&L, duration, max adverse/favorable excursion)
- Post-trade analysis

This data feeds the learning engine:
- Which strategies perform best per instrument?
- Which regime produces the most winners?
- What's the optimal confluence score threshold?
- Are there time-of-day patterns?
"""

# Storage architecture: SQLite for trades/signals (relational), JSON files for
# configuration/state (validated by Pydantic schemas in journal/schemas.py).
# Evaluated MongoDB/NoSQL in Session 10 — unnecessary complexity for current scale.

import json
import os
import shutil
from contextvars import ContextVar
from datetime import datetime, timezone, timedelta
from contextlib import contextmanager
from pathlib import Path
from sqlalchemy import (
    create_engine, Column, String, Float, Integer, Boolean, Text, DateTime,
    MetaData, Table, Index, ForeignKey, event
)
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker, scoped_session
from ..config import config


class Base(DeclarativeBase):
    pass


class SignalLog(Base):
    """Every signal generated by the system, even if no trade was taken."""
    __tablename__ = "signal_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10), nullable=False)
    regime = Column(String(20))
    composite_score = Column(Float, default=0.0)
    direction = Column(String(10))  # LONG, SHORT, or null
    agreeing_strategies = Column(Integer, default=0)
    total_strategies = Column(Integer, default=0)
    # JSON blob of all strategy signals
    signals_json = Column(Text)  # AUDIT: written by log_signal() but never read
    # Claude's decision
    claude_action = Column(String(10))  # BUY, SELL, SKIP
    claude_confidence = Column(Integer, default=0)
    claude_reasoning = Column(Text)  # AUDIT: written by log_signal() but never read
    # Risk manager result
    risk_passed = Column(Boolean, default=False)  # AUDIT: written by log_signal() but never read
    risk_rejections = Column(Text)  # AUDIT: written by log_signal() but never read
    # DE-03/DE-A01: Data lineage — trace signal back to the specific candle
    candle_timestamp = Column(DateTime)   # DE-A01: Now populated by log_signal()
    candle_close = Column(Float)          # DE-A01: Now populated by log_signal()
    # Final verdict
    should_trade = Column(Boolean, default=False)

    # DE-06: Add indexes for frequently queried columns
    __table_args__ = (
        Index("idx_signal_timestamp", "timestamp"),
        Index("idx_signal_symbol", "symbol"),
    )


class TradeLog(Base):
    """Completed trades — the core of the learning engine."""
    __tablename__ = "trade_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    # DE-07: Add foreign key for referential integrity
    signal_log_id = Column(Integer, ForeignKey("signal_logs.id"))
    opened_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    closed_at = Column(DateTime)
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10))
    direction = Column(String(10))  # LONG or SHORT
    regime = Column(String(20))
    # Prices
    entry_price = Column(Float)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    exit_price = Column(Float)
    position_size = Column(Float)
    # Phase 2: Broker-truth fields — actual fill data from exchange
    filled_price = Column(Float)          # Actual fill price from broker (may differ from entry_price)
    filled_quantity = Column(Float)       # Actual filled quantity from broker
    broker_order_id = Column(String(100)) # Exchange order ID for cross-reference
    contract_size = Column(Float, default=1.0)  # From InstrumentSpec, for P&L calculation
    # Results
    pnl = Column(Float, default=0.0)
    pnl_pct = Column(Float, default=0.0)
    duration_seconds = Column(Integer, default=0)
    max_favorable = Column(Float, default=0.0)  # Best unrealized P&L
    max_adverse = Column(Float, default=0.0)     # Worst unrealized P&L
    exit_reason = Column(String(20))  # tp_hit, sl_hit, manual, time
    # Strategy context
    confluence_score = Column(Float, default=0.0)
    claude_confidence = Column(Integer, default=0)
    strategies_agreed = Column(Text)  # JSON list of strategy names that agreed
    # Arena: which strategy proposed this trade
    proposing_strategy = Column(String(50))     # strategy name that found the setup
    strategy_score = Column(Float, default=0.0) # the strategy's signal score at entry
    strategy_factors = Column(Text)             # JSON: what factors aligned
    competing_proposals = Column(Integer, default=0)  # how many other strategies also proposed
    # Learning
    outcome_grade = Column(String(1))  # A, B, C, D, F
    lessons_learned = Column(Text)     # Claude's post-trade analysis

    # DE-06: Indexes for frequently queried columns
    __table_args__ = (
        Index("idx_trade_opened_at", "opened_at"),
        Index("idx_trade_symbol", "symbol"),
        Index("idx_trade_symbol_opened", "symbol", "opened_at"),
        Index("idx_trade_exit_price", "exit_price"),  # DE-F06
    )


class RiskState(Base):
    """
    Persisted risk manager state (Fix #8).
    Survives engine restarts so balance and daily P&L aren't lost.
    """
    __tablename__ = "risk_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    # Defaults match config.initial_balance (100K USD).
    # Actual values are written by RiskManager.record_trade_result().
    starting_balance = Column(Float, default=100_000.0)
    current_balance = Column(Float, default=100_000.0)
    total_pnl = Column(Float, default=0.0)
    peak_balance = Column(Float, default=100_000.0)


# CQ-01 FIX: Replace singleton session with session factory.
# Supports multiple database instances (production + lab).
_engines: dict[str, object] = {}
_factories: dict[str, object] = {}

# CQ-24 FIX: Use ContextVar so Lab and Production asyncio tasks each get their own
# "active db" without racing on a shared global. Each task's context is independent.
_active_db_key: ContextVar[str] = ContextVar("_active_db_key", default="default")


def _auto_migrate(eng) -> None:
    """Add columns that create_all() cannot apply to existing tables.

    Safe to run every startup — checks before adding each column.
    Only adds; never drops or renames.
    """
    import sqlite3 as _sqlite3

    # Extract raw file path from SQLAlchemy URL for sqlite3 PRAGMA
    url = str(eng.url)
    if ":memory:" in url or url.endswith(":memory:"):
        return  # In-memory DBs are always fresh — no migration needed

    db_file = url.replace("sqlite:///", "").replace("sqlite://", "")
    if not db_file:
        return

    migrations = [
        # Arena v3 columns (v1.7.0)
        ("proposing_strategy",  "ALTER TABLE trade_logs ADD COLUMN proposing_strategy TEXT"),
        ("strategy_score",      "ALTER TABLE trade_logs ADD COLUMN strategy_score REAL DEFAULT 0.0"),
        ("strategy_factors",    "ALTER TABLE trade_logs ADD COLUMN strategy_factors TEXT"),
        ("competing_proposals", "ALTER TABLE trade_logs ADD COLUMN competing_proposals INTEGER DEFAULT 0"),
        # Phase 2 broker-truth columns (v2.0.0)
        ("filled_price",        "ALTER TABLE trade_logs ADD COLUMN filled_price REAL"),
        ("filled_quantity",     "ALTER TABLE trade_logs ADD COLUMN filled_quantity REAL"),
        ("broker_order_id",     "ALTER TABLE trade_logs ADD COLUMN broker_order_id TEXT"),
        ("contract_size",       "ALTER TABLE trade_logs ADD COLUMN contract_size REAL DEFAULT 1.0"),
    ]

    try:
        conn = _sqlite3.connect(db_file)
        try:
            existing = {row[1] for row in conn.execute("PRAGMA table_info(trade_logs)").fetchall()}
            for col_name, ddl in migrations:
                if col_name not in existing:
                    conn.execute(ddl)
                    conn.commit()
        finally:
            conn.close()
    except Exception as e:
        import logging as _logging
        _logging.getLogger(__name__).warning("Schema auto-migration failed: %s", e)


def _init_db(db_key: str = "default", db_path: str | None = None):
    """Initialize a database engine and session factory.

    Args:
        db_key: Identifier for this DB instance ("default" for production, "lab" for lab).
        db_path: SQLite path override. If None, uses config.db_url.
    """
    if db_key in _engines:
        _active_db_key.set(db_key)
        return

    if db_path is None:
        db_path = config.db_url.replace("sqlite+aiosqlite:///", "sqlite:///")
    elif not db_path.startswith("sqlite"):
        db_path = f"sqlite:///{db_path}"

    eng = create_engine(db_path, echo=False)

    # Enable WAL mode for better concurrent read/write performance
    @event.listens_for(eng, "connect")
    def set_sqlite_pragma(dbapi_conn, connection_record):
        cursor = dbapi_conn.cursor()
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.close()

    Base.metadata.create_all(eng)

    # Auto-migrate: add columns introduced in v1.7.x and v2.0.0 that
    # create_all() cannot add to existing tables.
    _auto_migrate(eng)

    factory = scoped_session(sessionmaker(bind=eng))

    _engines[db_key] = eng
    _factories[db_key] = factory
    _active_db_key.set(db_key)


def init_lab_db(db_path: str | None = None):
    """Initialize the Lab database (separate from production).

    Call this at Lab engine startup. Uses a separate SQLite file
    so lab trades don't contaminate production data.
    """
    if db_path is None:
        db_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
            "notas_lave_lab.db"
        )
    _init_db(db_key="lab", db_path=db_path)


def use_db(db_key: str = "default"):
    """Switch which database subsequent get_db() calls use.

    CQ-24 FIX: Uses contextvars so each asyncio task (Lab vs Production)
    maintains its own active DB without racing on a shared global.
    """
    if db_key in _engines:
        _active_db_key.set(db_key)
    else:
        _init_db(db_key)


def get_db() -> Session:
    """
    Get a database session. Thread-safe via scoped_session.

    CQ-01: Each thread gets its own session from the factory.
    CQ-24: Uses the per-task ContextVar to pick the right DB.
    Sessions should be committed/rolled back by the caller.
    For simple read operations, the session auto-commits on close.

    NOTE: Prefer get_session() context manager for new code — it
    automatically commits/rollbacks/closes the session.
    """
    key = _active_db_key.get()
    if key not in _factories:
        _init_db(key)
    return _factories[key]()


@contextmanager
def get_session():
    """CQ-01: Context manager for short-lived sessions.

    Usage:
        with get_session() as db:
            db.query(...)
            db.commit()

    Sessions are automatically closed after the block, preventing
    stale data and resource leaks. Rollback on exception.
    CQ-24: Uses the per-task ContextVar to pick the right DB.
    """
    key = _active_db_key.get()
    if key not in _factories:
        _init_db(key)
    session = _factories[key]()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


def log_signal(
    symbol: str,
    timeframe: str,
    regime: str,
    composite_score: float,
    direction: str | None,
    agreeing: int,
    total: int,
    signals: list[dict],
    claude_action: str,
    claude_confidence: int,
    claude_reasoning: str,
    risk_passed: bool,
    risk_rejections: list[str],
    should_trade: bool,
    # DE-A01: Data lineage — trace signal to the candle that triggered it
    candle_timestamp: datetime | None = None,
    candle_close: float | None = None,
) -> int:
    """Log a signal evaluation. Returns the log ID."""
    db = get_db()
    entry = SignalLog(
        symbol=symbol,
        timeframe=timeframe,
        regime=regime,
        composite_score=composite_score,
        direction=direction,
        agreeing_strategies=agreeing,
        total_strategies=total,
        signals_json=json.dumps(signals),
        claude_action=claude_action,
        claude_confidence=claude_confidence,
        claude_reasoning=claude_reasoning,
        risk_passed=risk_passed,
        risk_rejections=json.dumps(risk_rejections),
        should_trade=should_trade,
        candle_timestamp=candle_timestamp,
        candle_close=candle_close,
    )
    db.add(entry)
    db.commit()
    return entry.id


def log_trade(
    signal_log_id: int,
    symbol: str,
    timeframe: str,
    direction: str,
    regime: str,
    entry_price: float,
    stop_loss: float,
    take_profit: float,
    position_size: float,
    confluence_score: float,
    claude_confidence: int,
    strategies_agreed: list[str],
    proposing_strategy: str = "",
    strategy_score: float = 0.0,
    strategy_factors: str = "",
    competing_proposals: int = 0,
    # Phase 2: Broker-truth fields
    filled_price: float | None = None,
    filled_quantity: float | None = None,
    broker_order_id: str | None = None,
    contract_size: float = 1.0,
) -> int:
    """Log a new trade. Returns the trade ID."""
    db = get_db()
    trade = TradeLog(
        signal_log_id=signal_log_id,
        symbol=symbol,
        timeframe=timeframe,
        direction=direction,
        regime=regime,
        entry_price=entry_price,
        stop_loss=stop_loss,
        take_profit=take_profit,
        position_size=position_size,
        filled_price=filled_price,
        filled_quantity=filled_quantity,
        broker_order_id=broker_order_id,
        contract_size=contract_size,
        confluence_score=confluence_score,
        claude_confidence=claude_confidence,
        strategies_agreed=json.dumps(strategies_agreed),
        proposing_strategy=proposing_strategy,
        strategy_score=strategy_score,
        strategy_factors=strategy_factors,
        competing_proposals=competing_proposals,
    )
    db.add(trade)
    db.commit()
    return trade.id


def close_trade(
    trade_id: int,
    exit_price: float,
    exit_reason: str,
    pnl: float,
    pnl_pct: float,
    duration_seconds: int,
    max_favorable: float = 0.0,
    max_adverse: float = 0.0,
):
    """Record trade outcome when it closes."""
    db = get_db()
    trade = db.query(TradeLog).filter(TradeLog.id == trade_id).first()
    if trade:
        trade.exit_price = exit_price
        trade.exit_reason = exit_reason
        trade.pnl = pnl
        trade.pnl_pct = pnl_pct
        trade.duration_seconds = duration_seconds
        trade.max_favorable = max_favorable
        trade.max_adverse = max_adverse
        trade.closed_at = datetime.now(timezone.utc)
        db.commit()


def get_recent_signals(limit: int = 50) -> list[dict]:
    """Get recent signal logs for the dashboard."""
    db = get_db()
    logs = db.query(SignalLog).order_by(SignalLog.id.desc()).limit(limit).all()
    return [
        {
            "id": l.id,
            "timestamp": l.timestamp.isoformat() if l.timestamp else None,
            "symbol": l.symbol,
            "timeframe": l.timeframe,
            "regime": l.regime,
            "score": l.composite_score,
            "direction": l.direction,
            "claude_action": l.claude_action,
            "claude_confidence": l.claude_confidence,
            "should_trade": l.should_trade,
        }
        for l in logs
    ]


def get_recent_trades(limit: int = 50) -> list[dict]:
    """Get recent trades for the dashboard."""
    db = get_db()
    trades = db.query(TradeLog).order_by(TradeLog.id.desc()).limit(limit).all()
    return [
        {
            "id": t.id,
            "opened_at": t.opened_at.isoformat() if t.opened_at else None,
            "closed_at": t.closed_at.isoformat() if t.closed_at else None,
            "symbol": t.symbol,
            "direction": t.direction,
            "regime": t.regime,
            "entry": t.entry_price,
            "exit": t.exit_price,
            "pnl": t.pnl,
            "pnl_pct": t.pnl_pct,
            "exit_reason": t.exit_reason,
            "confluence_score": t.confluence_score,
            "claude_confidence": t.claude_confidence,
            "grade": t.outcome_grade,
        }
        for t in trades
    ]


def get_strategy_performance() -> list[dict]:
    """Analyze which strategies contribute most to winning trades."""
    db = get_db()
    trades = db.query(TradeLog).filter(TradeLog.exit_price.isnot(None)).all()

    strategy_stats: dict[str, dict] = {}
    for t in trades:
        if not t.strategies_agreed:
            continue
        strategies = json.loads(t.strategies_agreed)
        for s in strategies:
            if s not in strategy_stats:
                strategy_stats[s] = {"wins": 0, "losses": 0, "total_pnl": 0.0}
            if t.pnl and t.pnl > 0:
                strategy_stats[s]["wins"] += 1
            else:
                strategy_stats[s]["losses"] += 1
            strategy_stats[s]["total_pnl"] += t.pnl or 0

    return [
        {
            "strategy": name,
            "wins": stats["wins"],
            "losses": stats["losses"],
            "total_trades": stats["wins"] + stats["losses"],
            "win_rate": stats["wins"] / max(stats["wins"] + stats["losses"], 1) * 100,
            "total_pnl": round(stats["total_pnl"], 2),
        }
        for name, stats in sorted(strategy_stats.items(), key=lambda x: x[1]["total_pnl"], reverse=True)
    ]


def save_risk_state(starting_balance: float, current_balance: float, total_pnl: float, peak_balance: float):
    """Save risk manager state to DB so it survives restarts (Fix #8)."""
    db = get_db()
    state = db.query(RiskState).first()
    if state:
        state.starting_balance = starting_balance
        state.current_balance = current_balance
        state.total_pnl = total_pnl
        state.peak_balance = peak_balance
        state.updated_at = datetime.now(timezone.utc)
    else:
        db.add(RiskState(
            starting_balance=starting_balance,
            current_balance=current_balance,
            total_pnl=total_pnl,
            peak_balance=peak_balance,
        ))
    db.commit()


def load_risk_state() -> dict | None:
    """Load risk state from DB on startup (Fix #8)."""
    db = get_db()
    state = db.query(RiskState).first()
    if state:
        return {
            "starting_balance": state.starting_balance,
            "current_balance": state.current_balance,
            "total_pnl": state.total_pnl,
            "peak_balance": state.peak_balance,
        }
    return None


def checkpoint_wal():
    """Run WAL checkpoint to keep WAL file size small.
    Should be called periodically (e.g., hourly).
    """
    for key, engine in list(_engines.items()):
        try:
            with engine.connect() as conn:
                conn.exec_driver_sql("PRAGMA wal_checkpoint(TRUNCATE)")
                conn.commit()
        except Exception:
            pass


def _get_db_path(db_key: str) -> str | None:
    """Get the filesystem path for a database engine."""
    engine = _engines.get(db_key)
    if engine is None:
        return None
    url = str(engine.url)
    # SQLite URLs look like: sqlite:///path/to/db.file
    if url.startswith("sqlite:///"):
        return url.replace("sqlite:///", "", 1)
    return None


def backup_database(db_key: str = "lab"):
    """Create a backup copy of the database file.
    Saves to engine/data/backups/ with date suffix.
    Keeps last 7 backups.
    """
    db_path = _get_db_path(db_key)
    if db_path is None or not os.path.exists(db_path):
        return

    # Determine backup directory: engine/data/backups/
    engine_dir = Path(__file__).resolve().parent.parent.parent  # engine/
    backup_dir = engine_dir / "data" / "backups"
    backup_dir.mkdir(parents=True, exist_ok=True)

    # Copy with date suffix
    db_name = Path(db_path).stem
    date_str = datetime.now().strftime("%Y%m%d")
    dest = backup_dir / f"{db_name}_{date_str}.db"
    shutil.copy2(db_path, dest)

    # Delete backups older than 7 days
    cutoff = datetime.now() - timedelta(days=7)
    for backup_file in sorted(backup_dir.glob(f"{db_name}_*.db")):
        try:
            mtime = datetime.fromtimestamp(backup_file.stat().st_mtime)
            if mtime < cutoff:
                backup_file.unlink()
        except OSError:
            pass


def run_db_maintenance():
    """Run periodic DB maintenance: checkpoint WAL + backup."""
    checkpoint_wal()
    backup_database("lab")
    backup_database("default")
